[package]
name = "machine-viewer"
version = "0.1.0"
authors = ["LifichiIsHungry <lifichi@protonmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.24.0"
risc-v = { path = "../risc-v" }